name: System Diagnostics (Metrics)
on:
  # 每天午夜自动更新
  schedule: [{cron: "0 0 * * *"}]
  # 允许手动触发
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # 核心配置：赛博朋克风
          user: lintsinghua
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          # 配色方案：Neon
          config_style: "background-color: #0d1117; color: #c9d1d9;"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage
          plugin_stars: yes
          filename: github-metrics.svg
